Update qvm-template-upgrade

diff --git a/qvm-template-upgrade b/qvm-template-upgrade
--- a/qvm-template-upgrade
+++ b/qvm-template-upgrade
@@ -4,7 +4,7 @@
 # Supports Fedora and Debian Templates
 # https://www.kennethrrosen.cloud
 #
-# Copyright (C) 2024 by Kenneth R. Rosen kennethrrosen@proton.me
+# Copyright (C) 2024 by Kenneth R. Rosen
 #
 # This program is free software; you can redistribute it and/or
 # modify it under the terms of the GNU General Public License; 
@@ -13,7 +13,7 @@
 #
 # This program is distributed in the hope that it will be useful,
 # but WITHOUT ANY WARRANTY; without even the implied warranty of
-# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 # GNU General Public License for more details.
 #
 # You should have received a copy of the GNU General Public License
@@ -44,7 +44,6 @@ Options:
 Examples:
   1. Upgrade a template or StandaloneVM 
      ${0##*/} TEMPLATE
-
   2. Upgrade a template or StandaloneVM, keeping original and cloning into a new template or StandaloneVM which will be upgraded:
      ${0##*/} TEMPLATE --clone --new-template=TEMPLATENEW
 
@@ -106,23 +105,45 @@ message() {
 
 handle_error() {
     local exit_code=$?
-    echo "An error occurred. Exiting with code $exit_code."
+    local last_command=$(history | tail -n 1 | sed -e 's/^[ ]*[0-9]\+[ ]*//')
+    echo "An error occurred. Exiting with code $exit_code. The last command was: $last_command"
     exit $exit_code
 }
 
 trap 'handle_error' ERR
 
 get_template_type() {
-    qvm-features "$1" os-distribution
+    local template=$1
+    local type
+    type=$(qvm-features "$template" os-distribution 2>/dev/null || qvm-run -p "$template" "cat /etc/os-release | grep ^ID=" | cut -d'=' -f2) || {
+        echo "unknown"
+        exit 1
+    }
+    if [[ -z "$type" || "$type" == "unknown" ]]; then
+        echo "Error: Could not determine template type for $template. It might be EOL." >&2
+        exit 1
+    fi
+    echo "$type"
 }
 
 get_template_version() {
-    qvm-features "$1" os-version
+    local template=$1
+    local version
+    version=$(qvm-features "$template" os-version 2>/dev/null || qvm-run -p "$template" "grep -oP '\d+' /etc/fedora-release || grep ^VERSION_CODENAME= /etc/os-release | cut -d'=' -f2") || {
+        echo "unknown"
+        exit 1
+    }
+    if [[ -z "$version" || "$version" == "unknown" ]]; then
+        echo "Error: Could not determine template version for $template. It might be EOL." >&2
+        exit 1
+    }
+    echo "$version"
 }
 
 next_debian_version() {
     local current_version=$1
     case $current_version in
+        buster) echo "bullseye" ;;
         bullseye) echo "bookworm" ;;
         bookworm) echo "trixie" ;;
         trixie) echo "fornextversion" ;;  # Update with the next version as necessary
@@ -201,15 +222,19 @@ if ! type qvm-ls >/dev/null 2>&1; then
     exit 1
 fi
 
+message "Determining template type and version..."
 template_type=$(get_template_type "$template")
 template_version=$(get_template_version "$template")
 
-if [[ -z "$template_type" ]]; then
+message "Template type: $template_type"
+message "Template version: $template_version"
+
+if [[ -z "$template_type" || "$template_type" == "unknown" ]]; then
     echo "Error: Could not determine template type for $template." >&2
     exit 1
 fi
 
-if [[ -z "$template_version" ]]; then
+if [[ -z "$template_version" || "$template_version" == "unknown" ]]; then
     echo "Error: Could not determine template version for $template." >&2
     exit 1
 fi
